version: '3.7'

services:
  laravel:
    build:
      args:
        user: admin
        uid: 1000
      context: ./laravel
      dockerfile: Dockerfile
    container_name: laravel
    restart: always
    tty: true
    volumes:
      - ./laravel-files:/var/www/laravel
    ports:
      - 9000:9000
    networks:
      - laranet
    depends_on:
      - db

  app:
    build:
      context: ./node
      dockerfile: Dockerfile.prod
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s sh -c "npm install && node index.js"
    restart: always
    tty: true
    volumes:
      - ./node:/usr/src/app
    ports:
      - 3000:3000
    networks:
      - laranet
    depends_on:
      - db
  
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - laranet
    depends_on:
      - laravel

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    networks:
      - laranet

networks:
  laranet:
    driver: bridge